version: '3.8'

services:
  agent:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      BITTE_API_KEY: ${BITTE_API_KEY}
      BITTE_AGENT_URL: http://localhost:3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    restart: unless-stopped

volumes:
  node_modules:
